language: php
php:
  - 5.4
  - 5.3

before_script:
  - pear channel-discover pearhub.org
  - pear install pearhub/Phactory
  - phpenv rehash

env:
  - DB=pdo/mysql

script: phpunit

notifications:
  email: false
